//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMtgSdkDotnet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ListOfSetLocation {
            get {
                return ((global::System.Drawing.Point)(this["ListOfSetLocation"]));
            }
            set {
                this["ListOfSetLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 200")]
        public global::System.Drawing.Size ListOfSetSize {
            get {
                return ((global::System.Drawing.Size)(this["ListOfSetSize"]));
            }
            set {
                this["ListOfSetSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10")]
        public global::System.Drawing.Point ListOfCardsLocation {
            get {
                return ((global::System.Drawing.Point)(this["ListOfCardsLocation"]));
            }
            set {
                this["ListOfCardsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 200")]
        public global::System.Drawing.Size ListOfCardsSize {
            get {
                return ((global::System.Drawing.Size)(this["ListOfCardsSize"]));
            }
            set {
                this["ListOfCardsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20, 20")]
        public global::System.Drawing.Point ListOfImagesLocation {
            get {
                return ((global::System.Drawing.Point)(this["ListOfImagesLocation"]));
            }
            set {
                this["ListOfImagesLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 200")]
        public global::System.Drawing.Size ListOfImagesSize {
            get {
                return ((global::System.Drawing.Size)(this["ListOfImagesSize"]));
            }
            set {
                this["ListOfImagesSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 30")]
        public global::System.Drawing.Point ViewUserInputLocation {
            get {
                return ((global::System.Drawing.Point)(this["ViewUserInputLocation"]));
            }
            set {
                this["ViewUserInputLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 200")]
        public global::System.Drawing.Size ViewUserInputSize {
            get {
                return ((global::System.Drawing.Size)(this["ViewUserInputSize"]));
            }
            set {
                this["ViewUserInputSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40")]
        public global::System.Drawing.Point ViewImageLocation {
            get {
                return ((global::System.Drawing.Point)(this["ViewImageLocation"]));
            }
            set {
                this["ViewImageLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 200")]
        public global::System.Drawing.Size ViewImageSize {
            get {
                return ((global::System.Drawing.Size)(this["ViewImageSize"]));
            }
            set {
                this["ViewImageSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50")]
        public global::System.Drawing.Point ViewTextLocation {
            get {
                return ((global::System.Drawing.Point)(this["ViewTextLocation"]));
            }
            set {
                this["ViewTextLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 200")]
        public global::System.Drawing.Size ViewTextSize {
            get {
                return ((global::System.Drawing.Size)(this["ViewTextSize"]));
            }
            set {
                this["ViewTextSize"] = value;
            }
        }
    }
}
